sudo: false
language: cpp
addons:
  apt:
    packages:
      - g++-multilib
      - libc6-dev:i386
compiler:
  - clang
before_script:
  - cd ..
  - git clone --depth=1 --branch=1.8-dev --recursive https://github.com/alliedmodders/sourcemod sourcemod-1.8
  - git clone --depth=1 --branch=master --recursive https://github.com/alliedmodders/ambuild
  - cd ambuild && python setup.py install --user
  - cd $TRAVIS_BUILD_DIR
  - git fetch --unshallow || true
  - ./breakpad.sh && export PATH=$PATH:$PWD/breakpad/build/src/tools/linux/dump_syms/
script:
  - mkdir build && cd build
  - python ../configure.py --enable-optimize
  - python ./build.py
after_success:
  - python ../upload.py
