version: '{build}'
os: Visual Studio 2015
environment:
  GYP_MSVS_VERSION: '2015'
install:
  - cd ..
  - git clone --depth=1 --branch=1.7-dev https://github.com/alliedmodders/sourcemod sourcemod-1.7
  - git clone --depth=1 --branch=master https://github.com/alliedmodders/ambuild
  - cd ambuild
  - C:\python27\python.exe setup.py install
  - cd %APPVEYOR_BUILD_FOLDER%
  - '"%VS140COMNTOOLS%\vsvars32.bat"'
  - breakpad.bat
build_script:
  - '"%VS140COMNTOOLS%\vsvars32.bat"'
  - mkdir build
  - cd build
  - C:\python27\python.exe ..\configure.py --enable-optimize
  - C:\python27\python.exe build.py
on_success:
  - C:\python27\python.exe ..\upload.py
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
